services:
  - type: web
    name: garena-guest-generator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true