services:
  - type: web
    name: sulavxguestmaker
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    healthCheckPath: /
    autoDeploy: true